### PR TITLE
pure RELU activations added

### PR DESCRIPTION
**Pull request by ghost**
this commit
[https://github.com/3DdeepAI/3DdeepAI/commit/d7764241ba357ca0ec581fa726fa75291e97017c#diff-8526a070794ac85f9da83e9dbf728cbf](https://github.com/3DdeepAI/3DdeepAI/commit/d7764241ba357ca0ec581fa726fa75291e97017c#diff-8526a070794ac85f9da83e9dbf728cbf)
only adds the RELU activations
(ignore all the other commits, I restored your original lenet.cu file with this commit 
[https://github.com/3DdeepAI/3DdeepAI/commit/b6c3b60e5e20f99955c6adbcbae02f3a052220b3#diff-8526a070794ac85f9da83e9dbf728cbf](https://github.com/3DdeepAI/3DdeepAI/commit/b6c3b60e5e20f99955c6adbcbae02f3a052220b3#diff-8526a070794ac85f9da83e9dbf728cbf)
so that the latest commit only contains all the changes for the added RELU activation

### CODE REVIEW

**Comment by tbennun** [comment]
There are 82 commits here and other files that have changed. Is it possible to create a new branch (in your fork) starting from my repo's latest commit, and only push one commit that changes lenet.cu?

Thanks :)

**Comment by tbennun** [comment]
Also, what is the quality of the training (i.e., what's the test error?)

**Comment by ghost** [comment]
ok, finally did it; will create a new PR with the new branch

**Comment by ghost** [comment]
the classification error remains at about 8-9% with this pure RELU activation adding

**Comment by ghost** [comment]
will do another new PR on this one:   https://github.com/3DdeepAI/3DdeepAI/tree/pureRELU

**Pull request closed without merging**
